### ISSUE TITLE
Doesn't work for local cars (Non-Custom)

### ISSUE THREAD

**Issue by Brotatochips11** [STACHY225/BabiczHandlingEditor#1]
The handling editor works as intended for all my servers import cars, but does not work for local cars such as the zentorno, or the sultan.

**Comment by STACHY225** [comment]
> The handling editor works as intended for all my servers import cars, but does not work for local cars such as the zentorno, or the sultan.

Are you sure? I just checked it on my server for multiple local vehicles and everything worked just fine. I think the best way to check if the script is working properly is to change the `fDriveBiasFront` value (is vehicle front, rear or all wheel drive) and see which wheels have the drive. Let me know if the problem still appears ;)

**Comment by Brotatochips11** [comment]
> > The handling editor works as intended for all my servers import cars, but does not work for local cars such as the zentorno, or the sultan.
> 
> Are you sure? I just checked it on my server for multiple local vehicles and everything worked just fine. I think the best way to check if the script is working properly is to change the `fDriveBiasFront` value (is vehicle front, rear or all wheel drive) and see which wheels have the drive. Let me know if the problem still appears ;)

Problem does still happen. It pulls up that cars handling meta, but any changes made do not take affect. So if the driveinertia is .25 and I change it to 10.0, close the editor, press left shift to re-open, it changed itself back to .25.

**Comment by Brotatochips11** [comment]
My discord is brotatochips11
I'd be more than happy to send you a video if you'd like.

**Comment by STACHY225** [comment]
Umm maybe don't change the values by such large numbers, try to make smaller changes, oh and make sure u typed /handling <vehname> at first // btw I added you on the discord
